import type { Metadata } from "next";
import { Header } from "@/components/Header/Header";
import styles from "./layout.module.css";
import { Footer } from "@/components/Footer/Footer";
import localFont from "next/font/local";

import "./globals.css";
// const inter = Inter({ subsets: ["latin"] });

const GTEestiProText = localFont({
    src: [
        {
            path: "../../public/fonts/GTEestiProText/gteestiprotext_regular.otf",
            weight: "400",
            style: "regular",
        },
        {
            path: "../../public/fonts/GTEestiProText/gteestiprotext_medium.otf",
            weight: "500",
            style: "medium",
        },
        {
            path: "../../public/fonts/GTEestiProText/gteestiprotext_bold.otf",
            weight: "700",
            style: "text_bold",
        },
    ],
    variable: "--gteestiprotext",
});
const GTEestiProDisplay = localFont({
    src: [
        {
            path: "../../public/fonts/GTEestiProDisplay/gteestiprodisplay_light.otf",
            weight: "300",
            style: "light",
        },
        {
            path: "../../public/fonts/GTEestiProDisplay/gteestiprodisplay_regular.otf",
            weight: "400",
            style: "regular",
        },
        {
            path: "../../public/fonts/GTEestiProDisplay/gteestiprodisplay_medium.otf",
            weight: "500",
            style: "medium",
        },
        {
            path: "../../public/fonts/GTEestiProDisplay/gteestiprodisplay_bold.otf",
            weight: "700",
            style: "bold",
        },
    ],
    variable: "--gteestiprodisplay",
});

export const metadata: Metadata = {
    title: "Job App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="ru">
            <body className={`${GTEestiProDisplay.className} ${GTEestiProText.variable} `}>
                <Header />
                {children}
                <Footer />
            </body>
        </html>
    );
}
